export const fonts = [
  {
    id: 1,
    name: "eUkraine Head",
    font: "font-eUkraineHead",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 2,
    name: "eUkraine",
    font: "font-eUkraine",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 20,
    name: "Core Rhino",
    font: "font-сoreRhino",
    weights: ["font-normal"],
  },
  {
    id: 6,
    name: "Rozetka",
    font: "font-rozetka",
    weights: ["font-normal", "font-bold"],
  },
  {
    id: 3,
    name: "Aptos",
    font: "font-aptos",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 4,
    name: "Aptos Narrow",
    font: "font-aptosNarrow",
    weights: ["font-normal", "font-bold"],
  },
  {
    id: 14,
    name: "FiraSans",
    font: "font-firaSans",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 17,
    name: "Panton",
    font: "font-panton",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 5,
    name: "Google Sans",
    font: "font-googleSans",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 10,
    name: "Tt First Neue",
    font: "font-tTFirstNeue",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 7,
    name: "MailSans",
    font: "font-mailSans",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 18,
    name: "Montserrat",
    font: "font-montserrat",
    weights: ["font-normal", "font-medium", "font-semibold", "font-bold"],
  },
  {
    id: 15,
    name: "VentiCF",
    font: "font-ventiCF",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 8,
    name: "MazzardH",
    font: "font-mazzardH",
    weights: ["font-normal", "font-medium", "font-semibold", "font-bold"],
  },
  {
    id: 14,
    name: "Cera Pro",
    font: "font-ceraPro",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 9,
    name: "Mont",
    font: "font-mont",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 16,
    name: "Rubik",
    font: "font-rubik",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 11,
    name: "JetBrains Mono",
    font: "font-jetBrainsMono",
    weights: ["font-normal", "font-medium", "font-bold"],
  },
  {
    id: 12,
    name: "Caveat",
    font: "font-caveat",
    weights: ["font-normal", "font-bold"],
  },
  {
    id: 13,
    name: "Anjhay",
    font: "font-anjhay",
    weights: ["font-normal"],
  },
  {
    id: 19,
    name: "Druk",
    font: "font-druk",
    weights: ["font-normal"],
  },
];

// 21
